[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
test = 'test'
ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]
gas_reports = ["*"]

solc_version='0.8.28'
optimizer = true
optimizer-runs = 200
via_ir = true

remappings = [
  '@openzeppelin/contracts/=lib/openzeppelin-contracts-upgradeable/lib/openzeppelin-contracts/contracts/',
  '@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/'
]

[rpc_endpoints]
goatMainnet = "https://rpc.goat.network"
goatTestnet = "https://rpc.testnet3.goat.network"
